services:
  - type: cron
    name: toon-theory-outreach
    env: python
    region: oregon
    schedule: "*/17 13-18 * * *"  # UTC is WAT -1
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: AIRTABLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
