name: Clean Blank Initial Leads

on:
  workflow_dispatch:  # ✅ Manual trigger only

concurrency:
  group: lead-pipeline
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  clean-blanks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run clean_blank_initials.py
        run: python clean_blank_initials.py

      - name: Commit cleaned leads
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add leads/scraped_leads.ndjson
          git diff --cached --quiet || git commit -m "🧼 Cleaned blank initials [bot]"
          git pull --rebase origin main || true
          git push

      - name: Emergency commit
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add leads/scraped_leads.ndjson
          git diff --cached --quiet || git commit -m "🧯 Emergency save after clean crash [bot]"
          git pull --rebase origin main || true
          git push || echo "❗ Emergency push failed"
