name: Clean Multi-Line NDJSON

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  contents: write  # Needed to commit changes

jobs:
  clean-leads:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run cleanup script
      run: python clean_ndjson.py

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add leads/scraped_leads.ndjson
        git commit -m "Cleaned NDJSON: removed emails and use cases for empty initial dates" || echo "No changes to commit"
        git push
