name: Run Decision Maker Scraper

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 12 * * 1-5' # Optional: runs every weekday at 12:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      SCRAPER_TABLE_NAME: ${{ secrets.SCRAPER_TABLE_NAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python decision_maker_scraper.py
