name: Generate Emails

on:
  workflow_dispatch:

concurrency:
  group: lead-pipeline
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  update-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (optional)
        run: pip install -r requirements.txt || true

      - name: Run email_generator.py
        run: python email_generator.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push
        run: |
          git add leads/scraped_leads.ndjson
          git diff --cached --quiet || git commit -m "✉️ Auto-update emails from generator [bot]"
          git pull --rebase origin main || true
          git push

      - name: Emergency commit
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add leads/scraped_leads.ndjson
          git diff --cached --quiet || git commit -m "🧯 Emergency email update save [bot]"
          git pull --rebase origin main || true
          git push || echo "❗ Emergency push failed"
