name: Extract Core Offerings

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -U google-generativeai python-dotenv

      - name: Run extract_services.py
        run: python extract_services.py

      - name: Commit updated leads
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add leads/scraped_leads.ndjson
          git commit -m "🔍 Auto-update services from Gemini [bot]" || echo "No changes"
          git push

      - name: Emergency commit in case of crash
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add leads/scraped_leads.ndjson
          git diff --cached --quiet || git commit -m "🧯 Emergency save after crash [bot]"
          git push || echo "❗ Push failed"
