name: Extract Core Offerings

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*.py', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -U groq python-dotenv

      - name: Run extract_services.py
        run: python extract_services.py

      - name: Commit updated leads
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add leads/scraped_leads.ndjson
          git commit -m "🔍 Auto-update services from Groq [bot]" || echo "No changes"
          # Retry git push up to 3 times with delay
          for i in 1 2 3; do
            git push && break || echo "Push failed, attempt $i/3" && sleep $((i * 10))
          done

      - name: Emergency commit in case of crash
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add leads/scraped_leads.ndjson
          git diff --cached --quiet || git commit -m "🧯 Emergency save after crash [bot]"
          # Retry git push up to 3 times with delay
          for i in 1 2 3; do
            git push && break || echo "Emergency push failed, attempt $i/3" && sleep $((i * 10))
          done
