name: Generate First Follow Ups

on:
  workflow_dispatch:

jobs:
  run-email-generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run Email Generator
        env:
          NOCODB_API_KEY: ${{ secrets.NOCODB_API_KEY }}
          NOCODB_OUTREACH_TABLE_ID: ${{ secrets.NOCODB_OUTREACH_TABLE_ID }}
          NOCODB_BASE_URL: ${{ secrets.NOCODB_BASE_URL }}
        run: python followup1_generator.py
