name: Generate First Follow Ups

on:
  workflow_dispatch:  # 🚫 manual trigger only

jobs:
  run-email-generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv requests

      - name: Run Email 2 Generator
        env:
          BASEROW_API_KEY: ${{ secrets.BASEROW_API_KEY }}
          BASEROW_DATABASE_ID: ${{ secrets.BASEROW_DATABASE_ID }}
          BASEROW_OUTREACH_TABLE: ${{ secrets.BASEROW_OUTREACH_TABLE }}
        run: python followup1_generator.py
