name: Generate Follow-Up 1 Emails

on:
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * *"  # Runs daily at 15:15 UTC — adjust as needed

jobs:
  run-followup1-generator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Follow-Up 1 Generator
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python generate_followup1.py
