name: Generate Followup Email 1

on:
  push:
    paths:
      - followup1_generator.py
      - .env
      - .github/workflows/email2_generator.yml
  workflow_dispatch:

jobs:
  run-email-generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install airtable-python-wrapper python-dotenv

      - name: Run Email 2 Generator
        env:
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
        run: python followup1_generator.py
