name: Generate Follow-up 1 Emails

on:
  workflow_dispatch:
  schedule:
    # Runs every weekday at 09:15 UTC (10:15 WAT)
    - cron: "15 9 * * 1-5"

jobs:
  generate-followup1:
    runs-on: ubuntu-latest

    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ✉️ Generate Follow-up 1 Emails
        run: python followup1_generator.py
