name: Generate Second Followups

on:
  workflow_dispatch:

jobs:
  followup2:
    runs-on: ubuntu-latest

    env:
      NOCODB_API_KEY: ${{ secrets.NOCODB_API_KEY }}
      NOCODB_OUTREACH_TABLE_ID: ${{ secrets.NOCODB_OUTREACH_TABLE_ID }}
      NOCODB_BASE_URL: ${{ secrets.NOCODB_BASE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install requests python-dotenv

      - name: Run Follow-up 2 Generator
        run: python followup2_generator.py
