name: Generate Use Case Inlines

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # 6:00 AM UTC daily — change as needed

jobs:
  generate-use-case-inlines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install git+https://github.com/groq/groq-python.git
          pip install python-dotenv airtable-python-wrapper

      - name: Run inline generator
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python generate_use_case_inlines.py
