name: Scrape Manifest Leads

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      SCRAPER_TABLE_NAME: ${{ secrets.SCRAPER_TABLE_NAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pyairtable playwright
          playwright install chromium

      - name: Run Manifest Scraper
        run: python manifest_scraper.py
