name: Send Initial Emails

on:
  workflow_dispatch:  # Manual only

jobs:
  send-emails:
    runs-on: ubuntu-latest

    env:
      BASEROW_API_KEY: ${{ secrets.BASEROW_API_KEY }}
      BASEROW_OUTREACH_TABLE: ${{ secrets.BASEROW_OUTREACH_TABLE }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: 🚀 Run sender script
        run: python sender.py
