name: Send Initial Emails

on:
  workflow_dispatch:

jobs:
  send-emails:
    runs-on: ubuntu-latest

    env:
      NOCODB_API_KEY: ${{ secrets.NOCODB_API_KEY }}
      NOCODB_OUTREACH_TABLE_ID: ${{ secrets.NOCODB_OUTREACH_TABLE_ID }}
      NOCODB_BASE_URL: ${{ secrets.NOCODB_BASE_URL }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests python-dotenv

      - name: Run sender script
        run: python sender.py
