name: Extract Core Offerings

on:
  workflow_dispatch:

jobs:
  extract-services:
    runs-on: ubuntu-latest

    env:
      NOCODB_API_KEY: ${{ secrets.NOCODB_API_KEY }}
      NOCODB_OUTREACH_TABLE_ID: ${{ secrets.NOCODB_OUTREACH_TABLE_ID }}
      NOCODB_BASE_URL: ${{ secrets.NOCODB_BASE_URL }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install python-dotenv groq requests

      - name: Run Service Extractor
        run: python services_extractor.py
