name: Summarize Web Copy

on:
  workflow_dispatch:  # 🔘 Manual trigger only

jobs:
  summarize:
    runs-on: ubuntu-latest

    env:
      BASEROW_API_KEY: ${{ secrets.BASEROW_API_KEY }}
      BASEROW_DATABASE_ID: ${{ secrets.BASEROW_DATABASE_ID }}
      BASEROW_TABLE_ID: ${{ secrets.BASEROW_TABLE_ID }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ✨ Run Groq summarizer
        run: python summarizer.py
